add support for rustls
nick42d/youtui pull request #26
Opened 2024-04-24 00:28 UTC by hungl6844

because openssl is a pain to cross-compile for, I have added the ability for users to switch to another backend instead. since the only configuration required to do so is enabling the features in reqwest, all I had to do was add a feature in ytmapi-rs that tells reqwest to switch the backend.

2024-04-24 12:33 UTC, nick42d commented
Hi @hungl6844 , cheers for the PR! Looks like there is a [GtiHub issue blocking CI](https://github.com/orgs/community/discussions/120966), bear with me while that gets resolved.

2024-04-24 12:35 UTC, nick42d commented
Does this approach still use reqwest default features by default? That's my preference for now.

2024-04-25 01:05 UTC, nick42d commented on ytmapi-rs/Cargo.lock
Please delete lockfile, not required for library (my mistake I need to add this to gitignore in future)

2024-04-25 01:06 UTC, nick42d commented on ytmapi-rs/Cargo.toml
> +reqwest = {version = "0.12.1", features = ["json"], default-features = false, optional = true}
Please add reqwest's non-tls related default features (e.g http2) https://docs.rs/reqwest/latest/reqwest/index.html

2024-04-25 01:07 UTC, nick42d commented on ytmapi-rs/Cargo.toml
> +reqwest = {version = "0.12.1", features = ["json"], default-features = false, optional = true}
Reqwest is required openssl or not, so should not be optional = true

2024-04-25 01:07 UTC, nick42d commented on ytmapi-rs/Cargo.toml
> +[features]
please add "default" feature that uses reqwest defaults (breaks youtui binary otherwise)

2024-04-25 01:10 UTC, nick42d requested changes
Added some comments

2024-04-25 15:27 UTC, hungl6844 commented
First of all, yes, by default, openssl is still used when building the binary, the feature “rusttls-tls” is required to switch away. Thanks for pointing out the issues, I didn’t even realize the binary wasn’t building (I was only using ytmapi-rs, so I never built youtui). I will implement your changes as soon as possible!

2024-04-26 14:17 UTC, nick42d approved these changes

2024-04-26 14:19 UTC, nick42d commented
Made some slight changes, if you're happy with that I'll get this merged!

2024-04-26 21:15 UTC, hungl6844 commented
Go for it!

2024-04-27 14:16 UTC, merged

2024-04-27 14:20 UTC, nick42d commented
> Go for it!

We're in - thanks for your contrib :)
In future I'll look to improve this slightly to work around case where multiple features are specified - issue #30 added for tracking.